//go:build darwin

package main

import (
	_ "embed"

	"github.com/getlantern/systray"
)

// icon_template.png is generated by build_all.sh (sips resize from assets/fendit.png).
// NSImage renders template images in the correct menu bar colour for light/dark mode.
//go:embed icon_template.png
var fenditIconPNG []byte

func setTrayIcon() {
	systray.SetTemplateIcon(fenditIconPNG, fenditIconPNG)
}
